### ISSUE TITLE
setMenu(null) throw an error

### ISSUE THREAD

**Issue by Armaldio** [patr0nus/DeskGap#25]
![image](https://user-images.githubusercontent.com/3089715/56073925-82987900-5d78-11e9-9c66-1f8959b1004e.png)

**Comment by patr0nus** [comment]
Could you show the full code that produces this error?

**Comment by Armaldio** [comment]
```js
const { app, BrowserWindow } = require('deskgap');

app.once('ready', () => {
  let mainWindow = new BrowserWindow({
    width : 1280,
    height: 720,
  });

  mainWindow.loadURL('https://discordapp.com/channels/@me');
  mainWindow.setMenu(null);

  // mainWindow.setMenu(null);
  // mainWindow.maximize();

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
});
```

**Comment by patr0nus** [comment]
Fixed in [https://github.com/patr0nus/DeskGap/commit/297972830b43d6f345db52722c938ebbe3e487a9](https://github.com/patr0nus/DeskGap/commit/297972830b43d6f345db52722c938ebbe3e487a9).
