### ISSUE TITLE
Cannot run on windows 10

### ISSUE THREAD

**Issue by kingvagabond** [patr0nus/DeskGap#4]
Unsupported OS version: 10.0.17134
The minimum supported OS version is 10.0.17763

**Comment by ghostslayer989** [comment]
### Supported Platforms:

> Windows 10 October 2018 Update (version 1809) or later

**Comment by patr0nus** [comment]
Windows 10.0.17134 (aka version 1803) supports the Win32 EdgeHTML webview, but doesn't support [AddPreLoadedScript](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.win32.ui.controls.iwebview.addpreloadedscript?view=win-comm-toolkit-dotnet-stable)/[AddInitializeScript](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.win32.ui.controls.iwebview.addinitializescript?view=win-comm-toolkit-dotnet-stable), which is essential for DeskGap to populate the `window.deskgap` object before loading any other scripts.
