### ISSUE TITLE
Unable to load localhost with loadUrl()

### ISSUE THREAD

**Issue by Blaconix** [patr0nus/DeskGap#50]
Hello,

I'm currently trying to run a Vue CLI 4 project inside DeskGap 0.3.0 using the following code:
```
const { app, BrowserWindow } = require('deskgap');

app.on('ready', () => {
    const win = new BrowserWindow({
      frame: false
    });
    // win.loadFile('index.html');
    win.loadURL('http://localhost:8080/')
});
```
Problem is that the URL is not loaded and instead I get about:blank. This only happens when I load localhost. When loading an external URL (example.com) everything works. I also have the exact same code in electron and it works.

Platform is Win 10 20H1 and Node 13.10.

**Comment by patr0nus** [comment]
This is a [limitation of EdgeHTML WebView](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2226). It can't access localhost servers.
