### ISSUE TITLE
Showing warning as potential Ransonware on TrendMicro

### ISSUE THREAD

**Issue by saisandeepvaddi** [patr0nus/DeskGap#6]
Seems related to #1 

TrendMicro is also warning as Ransomware.

![image](https://user-images.githubusercontent.com/13838175/52803256-ae84d000-304f-11e9-8a61-ee0973e10721.png)

**Comment by patr0nus** [comment]
As the screenshot suggested, the reason is "Newly Encountered Program Detected".

There's nothing much for DeskGap to do. It can be solved by signing the program before distributing to end-users.
