### ISSUE TITLE
Suggestion about linux implementation

### ISSUE THREAD

**Issue by jaredreich** [patr0nus/DeskGap#7]
Hey! Great work on this, super excited to try DeskGap on a personal project.

Perhaps you could find some ideas on how to add linux from this project: https://github.com/zserge/webview

**Comment by patr0nus** [comment]
This project looks interesting. I'll look into it. Thank you!

**Comment by navinSing** [comment]
Any rough timelines for linux ..

**Comment by patr0nus** [comment]
@navinSing Linux support has arrived.

**Comment by navinSing** [comment]
Super

**Comment by jaredreich** [comment]
Awesome stuff @patr0nus
